// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller/greeting.proto

package com.example.pojo.unary;

public final class Greeting {
  private Greeting() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_GreetingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_GreetingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_GreetingRequest_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_GreetingRequest_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_RejectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_RejectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_GreetingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_GreetingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031controller/greeting.proto\022\004grpc\032\034contr" +
      "oller/status_enum.proto\"\232\001\n\017GreetingRequ" +
      "est\022\017\n\007message\030\001 \001(\t\022\n\n\002no\030\002 \001(\005\022\016\n\006stat" +
      "us\030\003 \001(\010\022-\n\004data\030\004 \003(\0132\037.grpc.GreetingRe" +
      "quest.DataEntry\032+\n\tDataEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001\",\n\rRejectRequest\022\017\n" +
      "\007message\030\001 \001(\t\022\n\n\002no\030\002 \001(\005\"E\n\020GreetingRe" +
      "sponse\022\023\n\013description\030\001 \001(\t\022\034\n\006status\030\002 " +
      "\001(\0162\014.grpc.Status2\204\001\n\017GreetingService\0228\n" +
      "\005greet\022\025.grpc.GreetingRequest\032\026.grpc.Gre" +
      "etingResponse\"\000\0227\n\006reject\022\023.grpc.RejectR" +
      "equest\032\026.grpc.GreetingResponse\"\000B\032\n\026com." +
      "example.pojo.unaryP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.pojo.StatusEnum.getDescriptor(),
        });
    internal_static_grpc_GreetingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_GreetingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_GreetingRequest_descriptor,
        new java.lang.String[] { "Message", "No", "Status", "Data", });
    internal_static_grpc_GreetingRequest_DataEntry_descriptor =
      internal_static_grpc_GreetingRequest_descriptor.getNestedTypes().get(0);
    internal_static_grpc_GreetingRequest_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_GreetingRequest_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_grpc_RejectRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_RejectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_RejectRequest_descriptor,
        new java.lang.String[] { "Message", "No", });
    internal_static_grpc_GreetingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_GreetingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_GreetingResponse_descriptor,
        new java.lang.String[] { "Description", "Status", });
    com.example.pojo.StatusEnum.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
