// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller/greeting.proto

package com.example.pojo.unary;

public interface GreetingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GreetingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.grpc.Status status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.grpc.Status status = 2;</code>
   * @return The status.
   */
  com.example.pojo.Status getStatus();
}
