// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller/greeting.proto

package com.example.pojo.unary;

public interface GreetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GreetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 no = 2;</code>
   * @return The no.
   */
  int getNo();

  /**
   * <code>bool status = 3;</code>
   * @return The status.
   */
  boolean getStatus();

  /**
   * <code>map&lt;string, string&gt; data = 4;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, string&gt; data = 4;</code>
   */
  boolean containsData(
      java.lang.String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getData();
  /**
   * <code>map&lt;string, string&gt; data = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDataMap();
  /**
   * <code>map&lt;string, string&gt; data = 4;</code>
   */

  /* nullable */
java.lang.String getDataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; data = 4;</code>
   */

  java.lang.String getDataOrThrow(
      java.lang.String key);
}
