// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller/health_check_status.proto

package com.example.pojo;

public final class HealthCheckStatus {
  private HealthCheckStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$controller/health_check_status.proto\022\004" +
      "grpc\032\034controller/status_enum.proto\"\024\n\022He" +
      "althCheckRequest\"D\n\023HealthCheckResponse\022" +
      "\034\n\006status\030\001 \001(\0162\014.grpc.Status\022\017\n\007message" +
      "\030\002 \001(\t2T\n\022HealthCheckService\022>\n\005check\022\030." +
      "grpc.HealthCheckRequest\032\031.grpc.HealthChe" +
      "ckResponse\"\000B\024\n\020com.example.pojoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.pojo.StatusEnum.getDescriptor(),
        });
    internal_static_grpc_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_HealthCheckRequest_descriptor,
        new java.lang.String[] { });
    internal_static_grpc_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    com.example.pojo.StatusEnum.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
