// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller/health_check_status.proto

package com.example.pojo;

public interface HealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.HealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.grpc.Status status = 1;</code>
   * @return The status.
   */
  com.example.pojo.Status getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
