// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller/health_check_status.proto

package com.example.pojo;

public interface HealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.HealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {
}
